import { Button, ComboBox, SpinBox, CheckBox, VerticalBox, HorizontalBox, GroupBox, GridBox, LineEdit, TabWidget, ListView, StandardTableView } from "std-widgets.slint";

export enum SimModel {
    GBM,
    Bootstrap,
}

export struct SimParams {
    initial_price: float,
    horizon: int,
    num_paths: int,
    mu: float,
    sigma: float,
    seed: int,
    use_antithetic: bool,
    dt: int,
    model_type: string,
    is_portfolio: bool, // New flag
}

export struct SimStats {
    mean: float,
    std_dev: float,
    median: float,
    p5: float,
    p25: float,
    p75: float,
    p95: float,
    var95: float,
}

export struct PortfolioItem {
    ticker: string,
    weight: float,
}

export component AppWindow inherits Window {
    title: "Stock Monte Carlo Simulator";
    preferred-width: 1100px; // Widened slightly
    preferred-height: 750px;
    
    in-out property <[string]> ticker_list: [];
    in-out property <string> selected_ticker : "";
    in-out property <string> date_range: "Date range: N/A";
    in-out property <string> record_count: "Record count: 0";

    in-out property <float>  initial_price: 10000.0; // Default higher for portfolio
    in-out property <int> horizon: 30;
    in-out property <int> num_paths: 1000;
    in-out property <float> mu: 0.0002;
    in-out property <float> sigma: 0.015;
    in-out property <int> seed: 12345;
    in-out property <bool> use_antithetic: true;
    in-out property <string> model_type: "GBM";
    
    // NEW PORTFOLIO PROPERTIES
    in-out property <bool> is_portfolio_mode: false;
    in-out property <[PortfolioItem]> portfolio_model: [];
    in-out property <float> current_portfolio_weight: 0.0;
    in-out property <float> add_ticker_weight: 50.0;

    in property <SimStats> stats;
    in-out property <image> price_chart;
    in-out property <image> hist_chart;
    in-out property <string> exec_time: "0.0 ms";

    callback load_csv_pressed();
    callback select_ticker_changed();
    callback estimate_params_pressed();
    callback run_simulation_pressed(SimParams);
    callback export_summary_pressed();
    callback export_charts_pressed(); 
    
    // NEW CALLBACKS
    callback add_ticker_to_portfolio(string, float);
    callback clear_portfolio();

    HorizontalBox {
        padding: 10px;
        spacing: 10px;
        VerticalLayout { // Left Panel
            preferred-width: 320px;
            min-width: 300px;
            vertical-stretch: 1; 
            
            GroupBox {
                title: "Control Panel";
                vertical-stretch: 1; 
                VerticalBox {
                    spacing: 8px;
                    
                    // MODE SELECTOR
                    HorizontalLayout {
                        Text { text: "Mode: "; vertical-alignment: center; }
                        ComboBox {
                            model: ["Single Asset", "Portfolio"];
                            current-value: "Single Asset";
                            selected(val) => { 
                                root.is_portfolio_mode = (val == "Portfolio");
                            }
                        }
                    }

                    Text { text: "1. Data Input"; }
                    Button {
                        text: "Load CSV";
                        clicked => { load_csv_pressed(); } 
                    }
                    
                    // SINGLE ASSET UI
                    if (!root.is_portfolio_mode) : VerticalLayout {
                        spacing: 5px;
                        ComboBox { 
                            model: root.ticker_list;
                            selected(current-value) => {root.selected_ticker = current-value; select_ticker_changed();}
                        }
                        Text { text: root.date_range;}
                        Text { text: root.record_count;}
                        
                        Button {
                            text: "Estimate μ/σ from Data";
                            enabled: root.selected_ticker != "";
                            clicked => { estimate_params_pressed(); }
                        }
                    }

                    // PORTFOLIO UI
                    if (root.is_portfolio_mode) : VerticalLayout {
                        spacing: 5px;
                        Rectangle { 
                            background: #2c2c2c; 
                            border-radius: 4px;
                            vertical-stretch: 0;
                            height: 140px;
                            
                            VerticalLayout {
                                Text { text: "Portfolio Composition"; font-weight: 700; }
                                ListView {
                                    for item in root.portfolio_model : HorizontalBox {
                                        Text { text: item.ticker; width: 60px; }
                                        Text { text: item.weight + "%"; }
                                    }
                                }
                            }
                        }
                        Text { text: "Total Weight: " + root.current_portfolio_weight + "%"; color: root.current_portfolio_weight == 100.0 ? green : red; }
                        
                        HorizontalLayout {
                            ComboBox { 
                                width: 100px;
                                model: root.ticker_list;
                                selected(val) => { root.selected_ticker = val; }
                            }
                            SpinBox {
                                value: 0;
                                maximum: 100; 
                                minimum: 0;
                                step-size: 10;
                                edited(value) => {root.add_ticker_weight = value;}
                            }
                            Button {
                                text: "Add";
                                clicked => { root.add_ticker_to_portfolio(root.selected_ticker, root.add_ticker_weight); }
                            }
                        }
                        Button { text: "Clear Portfolio"; clicked => { root.clear_portfolio(); } }
                    }

                    Text { text: "3. Simulation Parameters";}
                    GridBox {
                        Row { 
                            Text { text: "Model:";} 
                            ComboBox {
                                model: ["GBM", "Bootstrap"];
                                selected => { root.model_type = self.current-value; }
                            } 
                        }
                        Row { 
                            Text { text: root.is_portfolio_mode ? "Total Capital:" : "Initial Price:";}
                            LineEdit { 
                                text: root.initial_price;
                                edited(text) => {root.initial_price = text.to-float();} 
                            } 
                        }
                        Row {                
                            Text { text: "Horizon (days):";}
                            SpinBox {
                                value <=> root.horizon;}
                        }
                        Row { 
                            Text { text: "Num Paths:";}
                            SpinBox {
                                value <=> root.num_paths;
                                maximum: 100000;
                                step-size: 100;
                            }
                        }
                        Row {                 
                            Text { text: "Random Seed:";}
                            SpinBox {
                                value <=> root.seed;
                                maximum: 100000;
                            }
                        }                        
                        // Parameters manual override (Only if NOT portfolio mode)
                        Row { 
                            Text { visible: !root.is_portfolio_mode; text: "Drift (μ) daily:";}
                            LineEdit { 
                                visible: !root.is_portfolio_mode;
                                text : root.mu;
                                edited(text) => {root.mu = text.to-float();}
                            } 
                        }
                        Row {                  
                            Text { visible: !root.is_portfolio_mode; text: "Volatility (σ) daily:";}
                            LineEdit { 
                                visible: !root.is_portfolio_mode;
                                text : root.sigma;
                                edited(text) => {root.sigma = text.to-float();} 
                            } 
                        }
                    }
                    CheckBox {
                        text: "Use Antithetic Variates";
                        checked <=> root.use_antithetic;
                    }
                    Button {
                        text: "RUN SIMULATION";
                        primary: true;
                        clicked => { run_simulation_pressed({
                            initial_price: root.initial_price,
                            horizon: root.horizon,
                            num_paths: root.num_paths,
                            mu: root.mu,
                            sigma: root.sigma,
                            seed: root.seed,
                            use_antithetic: root.use_antithetic,
                            dt: 1,
                            model_type: root.model_type,
                            is_portfolio: root.is_portfolio_mode
                        });
                        }
                    }
                }
            }
        }

        VerticalBox { // Middle Panel
            min-width: 400px;
            horizontal-stretch: 1;
            vertical-stretch: 1;
            GroupBox {
                title: "Visual Output";
                vertical-stretch: 1;
                TabWidget { 
                    vertical-stretch: 1;
                    Tab {
                        title: "Price Paths";
                        VerticalBox {
                            spacing: 10px;
                            padding: 5px;
                            Text { text: "Simulated Paths (50 Sample Scenarios)"; horizontal-alignment: center; }
                            Image { 
                                source <=> root.price_chart;
                                image-fit: fill;
                                vertical-stretch: 1;
                            }
                        }
                    }
                    Tab {
                        title: "Histogram";
                        VerticalBox {
                            spacing: 10px;
                            padding: 5px;
                            Text { text: "Distribution of Outcomes"; horizontal-alignment: center; }
                            Image { 
                                source <=> root.hist_chart;
                                image-fit: fill;
                                vertical-stretch: 1;
                            }
                        }
                    }
                }
            }
        }

        VerticalBox { // Right Panel
            preferred-width: 250px;
            min-width: 240px;
            vertical-stretch: 1;
            GroupBox {
                title: "Summary & Export";
                vertical-stretch: 1; 
                VerticalBox {
                    Text { text: "Statistical Summary"; }
                    GridBox {
                        Row { 
                            Text { text: "Mean:";} 
                            Text { text: "\{stats.mean}"; } 
                        }
                        Row { 
                            Text { text: "Std Dev:";} 
                            Text { text: "\{stats.std_dev}  "; } 
                        }
                        Row { 
                            Text { text: "Median (P50):";} 
                            Text { text: "\{stats.median} "; } 
                        }
                        Row { 
                            Text { text: "P5:";} 
                            Text { text: "\{stats.p5}  "; } 
                        }
                        Row { 
                            Text { text: "P25:";} 
                            Text { text: "\{stats.p25}  "; } 
                        }
                        Row { 
                            Text { text: "P75:";} 
                            Text { text: "\{stats.p75}  "; } 
                        }
                        Row { 
                            Text { text: "P95:";} 
                            Text { text: "\{stats.p95}  "; } 
                        }
                        Row { 
                            Text { text: "VaR 95%:";} 
                            Text { text: "\{stats.var95} "; } 
                        }
                    }
                    
                    Text { text: "Performance: ";}
                    Text { text: "Execution time: " + root.exec_time;}
                    Text { text: "Export Options";}
                    Button { 
                        text: "Save Summary (CSV)";
                        clicked => { export_summary_pressed(); } 
                    }
                    Button { 
                        text: "Save Charts (PNG)";
                        clicked => { export_charts_pressed(); } 
                    }
                }
            }
        }
    }
}